# YAML file containing all the scanner and medical image specific parameters retrieved from DICOM metadata
# This configuration file is specific for the MEDNERF chest scan, we use it for verification purposes

number_of_views: 72

# all following are in mm, the FOV is an estimate based on popular chest xray scanners
source_to_patient: 541
source_to_detector: 949
detector_size: 500
scanner_fov_x: 400
scanner_fov_y: 400
scanner_fov_z: 400

# next two are measured in pixels
height: 128
width: 128

# format output
output_format: "0000"
file_format: "png"
